### ISSUE TITLE
Errors while running

### ISSUE THREAD

**Issue by dhalloran1** [shirosaidev/sharesniffer#1] opened 2018-03-12 14:50 UTC
dan@heartofgold:~/Downloads/sharesniffer-master$ sudo python sharesniffer.py -l 4 --hosts 192.168.90.0/24 -a -m /mnt --smbuser tuser --smbpass testpass

         ____ _  _ ____ ____ ____          /
         ==== |--| |--| |--< |===         ["]  ,< ,,_      
         ____ __ _ _ ____ ____ ____ ____  [~]\/   |__|      
         ==== | \| | |--- |--- |=== |--<  OOO
         v0.1-b.1               

        

2018-03-12 10:38:34,624 [INFO][sniffshares] Sniffing for any network shares...
2018-03-12 10:38:34,624 [INFO][sniffshares] Hosts: 192.168.90.0/24
2018-03-12 10:38:34,641 [INFO][sniffshares] Starting network sniff...
2018-03-12 10:38:34,642 [INFO][sniffshares] Looking for nfs and smb shares...
Traceback (most recent call last):
  File "sharesniffer.py", line 488, in <module>
    shares = sniff_network()
  File "sharesniffer.py", line 320, in sniff_network
    shares['nfsshares'] = sniff.get_nfs_shares(hostlist_nfs)
  File "sharesniffer.py", line 94, in get_nfs_shares
    nfsshowmount = output['scan'][host]['tcp'][111]['script']['nfs-showmount'].strip().split('\n')
KeyError: 'script'

FYI I just put tuser and testpass in here as placeholders.
I am positive my SMB credentials are correct.  Can mount the same CIFS share to my NAS on my linux box using Gigolo.

**Comment by shirosaidev** [comment] 2018-03-17 16:20
It's possibly failing out looking for nmap scripts (.nse) in PATH (on Linux/macOS they are usually in /usr/local/share/nmap/), if you don't have the ones required are also in the rootdir of sharesniffer. Copy those to the same directory where you are running sharesniffer from and change into that directory and try running it from there.

**Comment by shirosaidev** [comment] 2018-06-08 14:19
this has been patched in v0.1-b.3

**Comment by shirosaidev** [comment] 2018-06-11 00:26
@dhalloran1 working for you now?

**Comment by shirosaidev** [comment] 2018-06-11 09:17
Duplicate of #3

**Comment by dhalloran1** [comment] 2018-06-11 21:12
Hey Chris,

Sorry for the delay.  I just got my first few render nodes installed in my
server rack.
Have to configure these puppies out, and go to NYC on Wednessday for a Fox
Audit.
Hopefully late this week I can download the new sharesniffer and give it a
go, I will let you know.
I'd also like to test out your diskover at some point too.  Our NAS is
approaching 4TB of its 22TB Raid 5
Its grown exponentially the past few weeks, and these even after archiving
/ offloading a few sizable projects.
Would love to see why with diskover / get a handle on things before it gets
too out of control.
Thanks again for all you do, seems like the SSA community really appreciate
your efforts.
Cheers!


*Daniel Halloran*
dhalloran@branchvfx.com

*IT Administrator | C:518 488 0960*
branch <https://www.branchvfx.com/> | 384 Broadway 2nd Fl. Albany NY 12207
<https://www.google.com/maps/place/384+Broadway,+Albany,+NY+12207/@42.6476449,-73.7527673,17z/data=!3m1!4b1!4m5!3m4!1s0x89de0a211d9eed07:0x12f3d8142e53d10d!8m2!3d42.647641!4d-73.7505786>

**Comment by shirosaidev** [comment] 2018-06-11 23:25
Thanks! If you want to spin up an OVA or docker image of diskover hit me up on SSA Slack.

**Closed as completed** 2018-06-15 07:12 UTC
